### ISSUE TITLE
Darwinia Relay guard client functions.

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/dj#53]
https://github.com/darwinia-network/darwinia-common/pull/192

**Comment by HackFisher** [comment]
@clearloop https://github.com/darwinia-network/darwinia.js/pull/54 Fixed this?

**Comment by clearloop** [comment]
The API of guard system in darwinia-network/darwinia-common#192 is outdated, #54 merged after it.

**Comment by HackFisher** [comment]
Need testing.
