### ISSUE TITLE
Member of first proposal should not be itself

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/dj#57]
https://github.com/darwinia-network/darwinia.js/blob/e93b3dd0c44f0d3507234a995c7108432889cdaf/packages/dj/src/proposal.ts#L118

recommended to use last confirm block:
```const target = await shadow.getProposal([last_confirm_block], block);```

**Comment by clearloop** [comment]
> recommended to use last confirm block:
> `const target = await shadow.getProposal([last_confirm_block], block);`

The liner relayer which is deprecated needs the `last_confirm_block`, the current relayer, we just relay.

**Comment by AurevoirXavier** [comment]
You should make sure the mmr root include last confirmed's mmr hash.
https://github.com/darwinia-network/darwinia-common/issues/252

**Comment by clearloop** [comment]
> You should make sure the mmr root include last confirmed's mmr hash.
> [darwinia-network/darwinia-common#252](https://github.com/darwinia-network/darwinia-common/issues/252)

So the uncle 19 has to be deleted now? LOL

**Comment by AurevoirXavier** [comment]
> So the uncle 19 has to be deleted now? LOL

Yes, on proposal.
