### ISSUE TITLE
Rename this repo to relayer

### ISSUE THREAD

**Issue by clearloop** [darwinia-network/dj#59]
## Desc

As a result of #55 , we decide to move `dactle` out of this repo and merge the left three packages, so the name `relayer` is more suitable now.

**Comment by AurevoirXavier** [comment]
This name sounds strange.

**Comment by clearloop** [comment]
> This name sounds strange.

Or `dj` straightly

**Comment by AurevoirXavier** [comment]
> This name sounds strange.

I don't know why, just feel strange.

How to define this repo? A relayer tool? (`relay-worker`?)

**Comment by AurevoirXavier** [comment]
If this repo is a toolset, I think dj is good.

```
dj relay-worker
dj relay-worker --enable-guard

dj ...
```

**Comment by HackFisher** [comment]
renamed to dj
